Change deprecated Logger.warn method
The documentation of the Python standard library [states](https://docs.python.org/3/library/logging.html#logging.Logger.warning):

    "Note: There is an obsolete method warn which is functionally identical to warning. As warn is deprecated, please do not use it - use warning instead."

Currently, publishing a message using a bad routing key on a channel *with enabled message delivery confirmations* yields a `DeprecationWarning`.

Input (example.py):

    import pika

    exchange = "test"
    queue = "test"
    message = "Hello, world"
    body = message.encode()
    routing_key = "bad_routing_key"

    with pika.BlockingConnection() as session:
        channel = session.channel()
        channel.confirm_delivery()
        channel.exchange_declare(exchange = exchange)
        channel.queue_declare(queue = queue)
        channel.queue_bind(exchange = exchange, queue = queue)
        channel.publish(exchange = exchange, routing_key = routing_key, body = body, mandatory = True)
        print("Produced message: {}".format(message))

Output (python3 -Wall example.py):

C:\Program Files (x86)\Python36-32\lib\site-packages\pika\adapters\blocking_connection.py:1284: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  len(body) if body is not None else None, body)
Traceback (most recent call last):
  File "produce.py", line 16, in <module>
    channel.publish(exchange = exchange, routing_key = routing_key, body = body, mandatory = True)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pika\adapters\blocking_connection.py", line 2131, in publish
    raise exceptions.UnroutableError(messages)
pika.exceptions.UnroutableError: 1 unroutable message(s) returned